# Generated by Django 4.1.3 on 2023-09-04 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0002_artist_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='metalhead',
            name='votes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='AlbumContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_management.album')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_management.member')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_management.role')),
            ],
        ),
    ]
