# Generated by Django 4.1.3 on 2023-09-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0003_member_role_alter_metalhead_votes_albumcontributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
