# Generated by Django 4.1.3 on 2023-09-05 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0007_artist_active_members_artist_all_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_management.album')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_management.member')),
                ('roles', models.ManyToManyField(related_name='roles_in_album', to='app_management.role')),
            ],
        ),
    ]
