# Generated by Django 4.1.3 on 2023-09-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0008_contributions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='active_members',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='all_members',
        ),
        migrations.AddField(
            model_name='member',
            name='active_on',
            field=models.ManyToManyField(related_name='active_groups', to='app_management.artist'),
        ),
        migrations.AddField(
            model_name='member',
            name='former_on',
            field=models.ManyToManyField(blank=True, related_name='former_groups', to='app_management.artist'),
        ),
    ]
