# Generated by Django 4.1.3 on 2023-09-06 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0010_alter_contributions_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributions',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='app_management.album'),
        ),
    ]
