# Generated by Django 4.1.3 on 2023-09-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0011_alter_contributions_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
