# Generated by Django 4.1.3 on 2023-09-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0012_artist_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='metalhead',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
