# Generated by Django 4.1.3 on 2023-09-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0013_album_slug_member_slug_metalhead_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metalhead',
            name='slug',
        ),
    ]
