# Generated by Django 4.1.3 on 2023-09-12 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0014_remove_metalhead_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(limit_value=0, message='The lowest rate is 0')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='active_on',
            field=models.ManyToManyField(blank=True, related_name='active_groups', to='app_management.artist'),
        ),
    ]
