# Generated by Django 4.1.3 on 2023-09-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0015_alter_album_rating_alter_member_active_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='subgenres',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
